/**
 * Company API methods
 *
 * Handles all company-related operations including CRUD and pagination.
 */

import { invoke } from '@tauri-apps/api/core';
import type { Company, CompanyCreate, CompanyUpdate, PaginatedResponse } from '../../types';

/**
 * Retrieves all companies from the database.
 * @returns Array of all company records
 */
export async function getCompanies(): Promise<Company[]> {
  try {
    const companies = await invoke<Company[]>('get_companies');
    return companies;
  } catch (error) {
    console.error('Failed to fetch companies from database:', error);
    throw error;
  }
}

/**
 * Fetches a paginated page of companies.
 * @param page - Page number (1-indexed)
 * @param pageSize - Number of items per page (default: 50)
 * @returns PaginatedResponse containing companies and metadata
 */
export async function getCompaniesPage(
  page: number = 1,
  pageSize: number = 50
): Promise<PaginatedResponse<Company>> {
  try {
    const response = await invoke<PaginatedResponse<Company>>('get_companies_page', {
      page,
      pageSize
    });
    return response;
  } catch (error) {
    console.error('Failed to fetch companies page:', error);
    throw error;
  }
}

/**
 * Fetches a single company by ID.
 * @param id - Company ID
 * @returns Company or null if not found
 */
export async function getCompanyById(id: string): Promise<Company | null> {
  try {
    const company = await invoke<Company | null>('get_company_by_id', { id });
    return company;
  } catch (error) {
    console.error('Failed to fetch company by ID:', error);
    throw error;
  }
}

/**
 * Creates a new company record in the database.
 * @param company - Company data without ID (will be generated by database)
 * @returns Created company or null on failure
 */
export async function createCompany(company: CompanyCreate): Promise<Company | null> {
  try {
    const newCompany = {
      name: company.name,
      name_short: company.name_short,
      abbreviation: company.abbreviation,
      city: company.city,
      country: company.country,
      reg_no: company.reg_no || null,
      tax_no: company.tax_no || null
    };

    const created = await invoke<Company>('create_company', { company: newCompany });
    return created;
  } catch (error) {
    console.error('Failed to create company:', error);
    return null;
  }
}

/**
 * Updates an existing company record with partial data.
 * @param id - SurrealDB record ID of the company to update
 * @param company - Partial company data (only changed fields)
 * @returns Updated company record
 */
export async function updateCompany(id: string, company: CompanyUpdate): Promise<Company | null> {
  try {
    const companyUpdate = {
      name: company.name || null,
      name_short: company.name_short || null,
      abbreviation: company.abbreviation || null,
      city: company.city || null,
      country: company.country || null,
      reg_no: company.reg_no || null,
      tax_no: company.tax_no || null
    };

    const updated = await invoke<Company>('update_company', { id, companyUpdate });
    return updated;
  } catch (error) {
    console.error('Failed to update company:', error);
    throw error;
  }
}

/**
 * Deletes a company record from the database.
 * @param id - SurrealDB record ID of the company to delete
 * @returns Deleted company record for confirmation
 */
export async function deleteCompany(id: string): Promise<Company | null> {
  try {
    const deleted = await invoke<Company>('delete_company', { id });
    return deleted;
  } catch (error) {
    console.error('Failed to delete company:', error);
    throw error;
  }
}
