/**
 * Contact API methods
 *
 * Handles all contact-related operations including CRUD and pagination.
 */

import { invoke } from '@tauri-apps/api/core';
import type { Contact, ContactCreate, ContactUpdate, PaginatedResponse } from '../../types';

/**
 * Retrieves all contacts from the database with company information.
 * @returns Array of all contact records with company data
 */
export async function getContacts(): Promise<Contact[]> {
  try {
    const contacts = await invoke<Contact[]>('get_contacts');
    return contacts;
  } catch (error) {
    console.error('Failed to fetch contacts from database:', error);
    throw error;
  }
}

/**
 * Fetches a paginated page of contacts.
 * @param page - Page number (1-indexed)
 * @param pageSize - Number of items per page (default: 50)
 * @returns PaginatedResponse containing contacts and metadata
 */
export async function getContactsPage(
  page: number = 1,
  pageSize: number = 50
): Promise<PaginatedResponse<Contact>> {
  try {
    const response = await invoke<PaginatedResponse<Contact>>('get_contacts_page', {
      page,
      pageSize
    });
    return response;
  } catch (error) {
    console.error('Failed to fetch contacts page:', error);
    throw error;
  }
}

/**
 * Fetches a single contact by ID.
 * @param id - Contact ID
 * @returns Contact or null if not found
 */
export async function getContactById(id: string): Promise<Contact | null> {
  try {
    const contact = await invoke<Contact | null>('get_contact_by_id', { id });
    return contact;
  } catch (error) {
    console.error('Failed to fetch contact by ID:', error);
    throw error;
  }
}

/**
 * Creates a new contact record in the database.
 * @param contact - Contact data without ID (will be generated by database)
 * @returns Created contact or null on failure
 */
export async function createContact(contact: ContactCreate): Promise<Contact | null> {
  try {
    const newContact = {
      ...contact,
      id: null
    };

    const created = await invoke<Contact>('create_contact', { contact: newContact });
    return created;
  } catch (error) {
    console.error('Failed to create contact:', error);
    return null;
  }
}

/**
 * Updates an existing contact with partial data.
 * @param id - Contact ID (string, extracted from SurrealDB Thing object)
 * @param contactUpdate - Partial contact data - only fields to update
 * @returns Updated contact or null on failure
 */
export async function updateContact(
  id: string,
  contactUpdate: ContactUpdate
): Promise<Contact | null> {
  try {
    const updated = await invoke<Contact>('update_contact', {
      id,
      contactUpdate
    });
    return updated;
  } catch (error) {
    console.error('Failed to update contact:', error);
    return null;
  }
}

/**
 * Deletes a contact from the database.
 * @param id - Contact ID (string, extracted from SurrealDB Thing object)
 * @returns Deleted contact or null on failure
 */
export async function deleteContact(id: string): Promise<Contact | null> {
  try {
    const deleted = await invoke<Contact>('delete_contact', { id });
    return deleted;
  } catch (error) {
    console.error('Failed to delete contact:', error);
    return null;
  }
}
