/**
 * Fee/RFP API methods
 *
 * Handles all fee proposal operations including CRUD, pagination,
 * and JSON export for InDesign integration.
 */

import { invoke } from '@tauri-apps/api/core';
import type { Fee, FeeCreate, FeeUpdate, PaginatedResponse } from '../../types';

/**
 * Retrieves all fee records from the database.
 * @returns Array of all fee records
 */
export async function getFees(): Promise<Fee[]> {
  try {
    const fees = await invoke<Fee[]>('get_fees');
    return fees;
  } catch (error) {
    console.error('Failed to fetch fees from database:', error);
    throw error;
  }
}

/**
 * Fetches a paginated page of fees.
 * @param page - Page number (1-indexed)
 * @param pageSize - Number of items per page (default: 50)
 * @returns PaginatedResponse containing fees and metadata
 */
export async function getFeesPage(
  page: number = 1,
  pageSize: number = 50
): Promise<PaginatedResponse<Fee>> {
  try {
    const response = await invoke<PaginatedResponse<Fee>>('get_fees_page', {
      page,
      pageSize
    });
    return response;
  } catch (error) {
    console.error('Failed to fetch fees page:', error);
    throw error;
  }
}

/**
 * Creates a new fee record in the database.
 * @param fee - Fee data without ID (will be generated by database)
 * @returns Created fee or null on failure
 */
export async function createFee(fee: FeeCreate): Promise<Fee | null> {
  try {
    const feeCreate = {
      name: fee.name,
      number: fee.number,
      rev: fee.rev,
      status: fee.status,
      issue_date: fee.issue_date,
      activity: fee.activity,
      package: fee.package,
      project_id:
        typeof fee.project_id === 'string'
          ? fee.project_id.replace('projects:', '')
          : fee.project_id?.toString() || '',
      company_id:
        typeof fee.company_id === 'string'
          ? fee.company_id.replace('company:', '')
          : fee.company_id?.toString() || '',
      contact_id:
        typeof fee.contact_id === 'string'
          ? fee.contact_id.replace('contacts:', '')
          : fee.contact_id?.toString() || '',
      staff_name: fee.staff_name,
      staff_email: fee.staff_email,
      staff_phone: fee.staff_phone,
      staff_position: fee.staff_position,
      strap_line: fee.strap_line,
      revisions: fee.revisions || []
    };

    const created = await invoke<Fee>('create_fee', { fee: feeCreate });
    return created;
  } catch (error) {
    console.error('Failed to create fee:', error);
    return null;
  }
}

/**
 * Updates an existing fee record in the database.
 * @param id - The string ID of the fee to update
 * @param fee - Complete fee data with updated fields
 * @returns Updated fee or null on failure
 */
export async function updateFee(id: string, fee: FeeUpdate): Promise<Fee | null> {
  try {
    const updatedFee = {
      ...fee,
      id: null,
      time: {
        updated_at: new Date().toISOString()
      }
    };

    const updated = await invoke<Fee>('update_fee', { id, fee: updatedFee });
    return updated;
  } catch (error) {
    console.error('Failed to update fee - API ERROR:', error);
    return null;
  }
}

/**
 * Deletes a fee record from the database.
 * @param id - The string ID of the fee to delete
 * @returns Deleted fee data for confirmation or null on failure
 */
export async function deleteFee(id: string): Promise<Fee | null> {
  try {
    const deleted = await invoke<Fee>('delete_fee', { id });
    return deleted;
  } catch (error) {
    console.error('Failed to delete fee:', error);
    return null;
  }
}

// =============================================================================
// JSON EXPORT METHODS
// =============================================================================

/**
 * Write fee proposal data to JSON file in project folder.
 *
 * Exports fee information to the project's JSON template file
 * for InDesign integration.
 *
 * @param feeId - The ID of the fee to export (e.g., '24_96606_1')
 * @returns Success message with file path, or null on error
 */
export async function writeFeeToJson(feeId: string): Promise<string | null> {
  try {
    const result = await invoke<string>('write_fee_to_json', { rfpId: feeId });
    return result;
  } catch (error) {
    console.error('Failed to write RFP data to JSON:', error);
    return null;
  }
}

/**
 * Write fee proposal data to JSON file with enhanced safety checks.
 *
 * This enhanced version includes safety mechanisms to detect and protect
 * existing project data while allowing safe overwriting of placeholder content.
 * It automatically creates timestamped backups when real project data is detected.
 *
 * @param feeId - The ID of the fee proposal to export (e.g., "fee:some_id")
 * @returns Success message with safety actions taken, or null on error
 */
export async function writeFeeToJsonSafe(feeId: string): Promise<string | null> {
  try {
    const result = await invoke<string>('write_fee_to_json_safe', { feeId });
    return result;
  } catch (error) {
    console.error('Failed to write fee data to JSON with safety checks:', error);
    return null;
  }
}
