/**
 * Fee/RFP API methods
 *
 * Handles all fee proposal operations including CRUD, pagination,
 * and JSON export for InDesign integration.
 */

import { invoke } from '@tauri-apps/api/core';
import type { Fee, FeeCreate, FeeUpdate, PaginatedResponse } from '../../types';
import type { PricingBreakdown, PostContractItem, ReimbursableCost, PaymentSchedule } from '../../types/database';
import { logApiError } from '../services/logger';

/**
 * Pricing update payload - contains only pricing-related fields.
 */
export interface PricingUpdate {
  pricing?: PricingBreakdown;
  post_contract_items?: PostContractItem[];
  reimbursable_costs?: ReimbursableCost[];
  payment_schedule?: PaymentSchedule;
}

/**
 * Retrieves all fee records from the database.
 * @returns Array of all fee records
 */
export async function getFees(): Promise<Fee[]> {
  try {
    const fees = await invoke<Fee[]>('get_fees');
    return fees;
  } catch (error) {
    logApiError('getFees', error as Error, { component: 'FeesApi' });
    throw error;
  }
}

/**
 * Fetches a paginated page of fees.
 * @param page - Page number (1-indexed)
 * @param pageSize - Number of items per page (default: 50)
 * @returns PaginatedResponse containing fees and metadata
 */
export async function getFeesPage(
  page: number = 1,
  pageSize: number = 50
): Promise<PaginatedResponse<Fee>> {
  try {
    const response = await invoke<PaginatedResponse<Fee>>('get_fees_page', {
      page,
      pageSize
    });
    return response;
  } catch (error) {
    logApiError('getFeesPage', error as Error, { component: 'FeesApi' });
    throw error;
  }
}

/**
 * Creates a new fee record in the database.
 * @param fee - Fee data without ID (will be generated by database)
 * @returns Created fee
 * @throws Error if creation fails
 */
export async function createFee(fee: FeeCreate): Promise<Fee> {
  try {
    const feeCreate = {
      name: fee.name,
      number: fee.number,
      rev: fee.rev,
      status: fee.status,
      issue_date: fee.issue_date,
      activity: fee.activity,
      package: fee.package,
      project_id: (fee.project_id || '').replace('projects:', ''),
      company_id: (fee.company_id || '').replace('company:', ''),
      contact_id: (fee.contact_id || '').replace('contacts:', ''),
      staff_name: fee.staff_name,
      staff_email: fee.staff_email,
      staff_phone: fee.staff_phone,
      staff_position: fee.staff_position,
      strap_line: fee.strap_line,
      revisions: fee.revisions || []
    };

    const created = await invoke<Fee>('create_fee', { fee: feeCreate });
    return created;
  } catch (error) {
    logApiError('createFee', error as Error, { component: 'FeesApi' });
    throw error;
  }
}

/**
 * Updates an existing fee record in the database.
 * @param id - The string ID of the fee to update
 * @param fee - Complete fee data with updated fields
 * @returns Updated fee
 * @throws Error if update fails
 */
export async function updateFee(id: string, fee: FeeUpdate): Promise<Fee> {
  try {
    const updatedFee = {
      ...fee,
      id: null,
      time: {
        updated_at: new Date().toISOString()
      }
    };

    const updated = await invoke<Fee>('update_fee', { id, fee: updatedFee });
    return updated;
  } catch (error) {
    logApiError('updateFee', error as Error, { component: 'FeesApi' });
    throw error;
  }
}

/**
 * Deletes a fee record from the database.
 * @param id - The string ID of the fee to delete
 * @returns Deleted fee data for confirmation
 * @throws Error if deletion fails
 */
export async function deleteFee(id: string): Promise<Fee> {
  try {
    const deleted = await invoke<Fee>('delete_fee', { id });
    return deleted;
  } catch (error) {
    logApiError('deleteFee', error as Error, { component: 'FeesApi' });
    throw error;
  }
}

/**
 * Updates only the pricing-related fields of a fee proposal.
 * This is more efficient than updateFee when only pricing data changes.
 * @param id - The string ID of the fee to update
 * @param pricing - Partial pricing data to update
 * @returns Updated fee
 * @throws Error if update fails
 */
export async function updateFeePricing(id: string, pricing: PricingUpdate): Promise<Fee> {
  try {
    const updated = await invoke<Fee>('update_fee_pricing', { id, pricing });
    return updated;
  } catch (error) {
    logApiError('updateFeePricing', error as Error, { component: 'FeesApi' });
    throw error;
  }
}

// =============================================================================
// JSON EXPORT METHODS
// =============================================================================

/**
 * Write fee proposal data to JSON file in project folder.
 *
 * Exports fee information to the project's JSON template file
 * for InDesign integration.
 *
 * @param feeId - The ID of the fee to export (e.g., '24_96606_1')
 * @returns Success message with file path
 * @throws Error if export fails
 */
export async function writeFeeToJson(feeId: string): Promise<string> {
  try {
    const result = await invoke<string>('write_fee_to_json', { rfpId: feeId });
    return result;
  } catch (error) {
    logApiError('writeFeeToJson', error as Error, { component: 'FeesApi' });
    throw error;
  }
}

/**
 * Write fee proposal data to JSON file with enhanced safety checks.
 *
 * This enhanced version includes safety mechanisms to detect and protect
 * existing project data while allowing safe overwriting of placeholder content.
 * It automatically creates timestamped backups when real project data is detected.
 *
 * @param feeId - The ID of the fee proposal to export (e.g., "fee:some_id")
 * @returns Success message with safety actions taken
 * @throws Error if export fails
 */
export async function writeFeeToJsonSafe(feeId: string): Promise<string> {
  try {
    const result = await invoke<string>('write_fee_to_json_safe', { feeId });
    return result;
  } catch (error) {
    logApiError('writeFeeToJsonSafe', error as Error, { component: 'FeesApi' });
    throw error;
  }
}
