/**
 * Project API methods
 *
 * Handles all project-related operations including CRUD, pagination,
 * project numbering, and template management.
 */

import { invoke } from '@tauri-apps/api/core';
import type { Project, ProjectCreate, ProjectUpdate, PaginatedResponse } from '../../types';
import { logApiError } from '../services/logger';

/**
 * Retrieves all projects from the database.
 * @returns Array of all project records
 */
export async function getProjects(): Promise<Project[]> {
  try {
    const projects = await invoke<Project[]>('get_projects');
    return projects;
  } catch (error) {
    logApiError('getProjects', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}

/**
 * Fetches a paginated page of projects.
 * @param page - Page number (1-indexed)
 * @param pageSize - Number of items per page (default: 50)
 * @returns PaginatedResponse containing projects and metadata
 */
export async function getProjectsPage(
  page: number = 1,
  pageSize: number = 50
): Promise<PaginatedResponse<Project>> {
  try {
    const response = await invoke<PaginatedResponse<Project>>('get_projects_page', {
      page,
      pageSize
    });
    return response;
  } catch (error) {
    logApiError('getProjectsPage', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}

/**
 * Fetches a single project by ID.
 * @param id - Project ID
 * @returns Project or null if not found
 */
export async function getProjectById(id: string): Promise<Project | null> {
  try {
    const project = await invoke<Project | null>('get_project_by_id', { id });
    return project;
  } catch (error) {
    logApiError('getProjectById', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}

/**
 * Searches projects by name, location, or project number.
 * @param query - Search term to match against project fields
 * @returns Array of matching project records
 */
export async function searchProjects(query: string): Promise<Project[]> {
  try {
    const projects = await invoke<Project[]>('search_projects', { query });
    return projects;
  } catch (error) {
    logApiError('searchProjects', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}

/**
 * Creates a new project record in the database.
 * @param project - Project data without ID (will be generated by database)
 * @returns Created project
 * @throws Error if creation fails
 */
export async function createProject(project: ProjectCreate): Promise<Project> {
  try {
    const newProject = {
      ...project,
      id: null,
      time: {
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      }
    };

    const created = await invoke<Project>('create_project', { project: newProject });
    return created;
  } catch (error) {
    logApiError('createProject', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}

/**
 * Updates an existing project record.
 * @param id - Project ID
 * @param projectData - Updated project data
 * @returns Updated project
 */
export async function updateProject(id: string, projectData: ProjectUpdate): Promise<Project> {
  try {
    const updated = await invoke<Project>('update_project', { id, projectUpdate: projectData });
    return updated;
  } catch (error) {
    logApiError('updateProject', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}

/**
 * Deletes a project record from the database.
 * @param id - Project ID
 * @returns Deleted project data
 */
export async function deleteProject(id: string): Promise<Project> {
  try {
    const deleted = await invoke<Project>('delete_project', { id });
    return deleted;
  } catch (error) {
    logApiError('deleteProject', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}

// =============================================================================
// PROJECT NUMBERING METHODS
// =============================================================================

/**
 * Generates the next sequential project number for a country.
 *
 * Project numbers follow the format YY-CCCNN where:
 * - YY: Two-digit year
 * - CCC: Country dial code
 * - NN: Sequential number
 *
 * @param countryName - Full country name to lookup dial code
 * @param year - Optional year override (defaults to current year)
 * @returns Generated project number (e.g., "25-97105")
 */
export async function generateNextProjectNumber(
  countryName: string,
  year?: number
): Promise<string> {
  try {
    const projectNumber = await invoke<string>('generate_next_project_number', {
      countryName,
      year: year || null
    });
    return projectNumber;
  } catch (error) {
    logApiError('generateNextProjectNumber', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}

/**
 * Validates that a project number is unique and follows correct format.
 * @param projectNumber - Project number to validate (e.g., "25-97105")
 * @returns True if valid and unique, false otherwise
 */
export async function validateProjectNumber(projectNumber: string): Promise<boolean> {
  try {
    const isValid = await invoke<boolean>('validate_project_number', { projectNumber });
    return isValid;
  } catch (error) {
    logApiError('validateProjectNumber', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}

// =============================================================================
// PROJECT TEMPLATE METHODS
// =============================================================================

/**
 * Creates a new project with automatic template folder copying.
 * @param project - Partial project data (number will be generated)
 * @returns Created project with template folder
 */
export async function createProjectWithTemplate(project: Partial<Project>): Promise<Project> {
  try {
    const created = await invoke<Project>('create_project_with_template', { project });
    return created;
  } catch (error) {
    logApiError('createProjectWithTemplate', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}

/**
 * Copy project template folder and rename files.
 * @param projectNumber - Project number (e.g., "24-96606")
 * @param projectShortName - Project short name (e.g., "Test Project")
 * @returns Success message with folder path
 */
export async function copyProjectTemplate(
  projectNumber: string,
  projectShortName: string
): Promise<string> {
  try {
    const result = await invoke<string>('copy_project_template', {
      projectNumber,
      projectShortName
    });
    return result;
  } catch (error) {
    logApiError('copyProjectTemplate', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}

/**
 * Populate project data from FP record and rename JSON file.
 * @param fpId - FP record ID (e.g., "fee:24_96606_1")
 * @param projectNumber - Project number (e.g., "24-96606")
 * @param projectShortName - Project short name (e.g., "Test Project")
 * @returns Success message with update details
 */
export async function populateProjectData(
  fpId: string,
  projectNumber: string,
  projectShortName: string
): Promise<string> {
  try {
    const result = await invoke<string>('populate_project_data', {
      fpId,
      projectNumber,
      projectShortName
    });
    return result;
  } catch (error) {
    logApiError('populateProjectData', error as Error, { component: 'ProjectsApi' });
    throw error;
  }
}
