/**
 * Venue API methods
 *
 * Handles all venue-related operations including CRUD and pagination.
 * Venues represent physical places where projects are located.
 */

import { invoke } from '@tauri-apps/api/core';
import type { Venue, VenueCreate, PaginatedResponse, Project } from '../../types';
import { logApiError } from '../services/logger';

/**
 * Retrieves all venues from the database, ordered by name.
 * @returns Array of all venue records
 */
export async function getVenues(): Promise<Venue[]> {
  try {
    const venues = await invoke<Venue[]>('get_venues');
    return venues;
  } catch (error) {
    logApiError('getVenues', error as Error, { component: 'VenuesApi' });
    throw error;
  }
}

/**
 * Fetches a paginated page of venues.
 * @param page - Page number (1-indexed)
 * @param pageSize - Number of items per page (default: 50)
 * @returns PaginatedResponse containing venues and metadata
 */
export async function getVenuesPage(
  page: number = 1,
  pageSize: number = 50
): Promise<PaginatedResponse<Venue>> {
  try {
    const response = await invoke<PaginatedResponse<Venue>>('get_venues_page', {
      page,
      pageSize
    });
    return response;
  } catch (error) {
    logApiError('getVenuesPage', error as Error, { component: 'VenuesApi' });
    throw error;
  }
}

/**
 * Fetches a single venue by ID.
 * @param id - Venue ID
 * @returns Venue or null if not found
 */
export async function getVenueById(id: string): Promise<Venue | null> {
  try {
    const venue = await invoke<Venue | null>('get_venue_by_id', { id });
    return venue;
  } catch (error) {
    logApiError('getVenueById', error as Error, { component: 'VenuesApi' });
    throw error;
  }
}

/**
 * Creates a new venue record in the database.
 * @param venue - Venue data without ID (will be generated by database)
 * @returns Created venue with database-assigned ID and timestamps
 */
export async function createVenue(venue: VenueCreate): Promise<Venue> {
  try {
    const created = await invoke<Venue>('create_venue', {
      name: venue.name,
      nameShort: venue.name_short || null,
      city: venue.location?.city || null,
      country: venue.location?.country || null,
      area: venue.location?.area || null,
      tags: venue.tags || null,
      notes: venue.notes || null,
    });
    return created;
  } catch (error) {
    logApiError('createVenue', error as Error, { component: 'VenuesApi' });
    throw error;
  }
}

/**
 * Updates an existing venue record.
 * @param id - Venue record ID
 * @param venue - Updated venue data
 * @returns Updated venue record
 */
export async function updateVenue(id: string, venue: Partial<VenueCreate>): Promise<Venue> {
  try {
    const updated = await invoke<Venue>('update_venue', {
      id,
      name: venue.name || '',
      nameShort: venue.name_short || null,
      city: venue.location?.city || null,
      country: venue.location?.country || null,
      area: venue.location?.area || null,
      tags: venue.tags || null,
      notes: venue.notes || null,
    });
    return updated;
  } catch (error) {
    logApiError('updateVenue', error as Error, { component: 'VenuesApi' });
    throw error;
  }
}

/**
 * Deletes a venue from the database.
 * Will fail if there are projects linked to this venue.
 * @param id - Venue record ID to delete
 * @returns The deleted venue data
 */
export async function deleteVenue(id: string): Promise<Venue> {
  try {
    const deleted = await invoke<Venue>('delete_venue', { id });
    return deleted;
  } catch (error) {
    logApiError('deleteVenue', error as Error, { component: 'VenuesApi' });
    throw error;
  }
}

/**
 * Gets all projects linked to a specific venue.
 * @param venueId - The venue ID to look up projects for
 * @returns Projects linked to the venue
 */
export async function getProjectsForVenue(venueId: string): Promise<Project[]> {
  try {
    const projects = await invoke<Project[]>('get_projects_for_venue', { venueId });
    return projects;
  } catch (error) {
    logApiError('getProjectsForVenue', error as Error, { component: 'VenuesApi' });
    throw error;
  }
}
